//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class boun
    {
        public int bouns_id { get; set; }
        public System.DateTime bouns_date { get; set; }
        public int employee_id { get; set; }
        public string bouns_reason { get; set; }
        public int bouns_static_value { get; set; }
        public int bouns_per_value { get; set; }
        public int created_by { get; set; }
        public int last_modified_by { get; set; }
        public int status { get; set; }
    }
}
