//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_users_cuts
    {
        public int cut_id { get; set; }
        public int user_id { get; set; }
        public int cut_type { get; set; }
        public double cut_value { get; set; }
        public string cut_reason { get; set; }
        public System.DateTime cut_date { get; set; }
        public sbyte cut_details { get; set; }
    }
}
