//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_users_bonous
    {
        public int bonous_id { get; set; }
        public int user_id { get; set; }
        public int bonous_type { get; set; }
        public double bonous_value { get; set; }
        public string bonous_reason { get; set; }
        public System.DateTime bonous_date { get; set; }
        public string accepted { get; set; }
    }
}
