//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_drivers_and_supervisors
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public int user_type { get; set; }
        public string user_social_id { get; set; }
        public string user_driving_license_number { get; set; }
        public System.DateTime user_driving_license_due_date { get; set; }
        public string user_driving_license_type { get; set; }
        public double salary { get; set; }
        public string personal_mobile { get; set; }
        public string school_mobile { get; set; }
        public Nullable<System.DateTime> employment_date { get; set; }
        public string EnglishName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FamilyName { get; set; }
    }
}
