//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_users_monthly_salaries
    {
        public int user_id { get; set; }
        public int salary_month { get; set; }
        public int salary_year { get; set; }
        public double salary { get; set; }
        public double cutsDays { get; set; }
        public double cutsDaysValue { get; set; }
        public double cutsValues { get; set; }
        public double total { get; set; }
    }
}
