//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeedependant
    {
        public int DependantID { get; set; }
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Type { get; set; }
        public string InsuranceProgram { get; set; }
        public Nullable<int> InsuranceRate { get; set; }
        public Nullable<decimal> InsuranceConcession { get; set; }
        public Nullable<int> InsuranceMonthly { get; set; }
        public Nullable<System.DateTime> InsuranceActiveDate { get; set; }
    }
}
