//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_fin
    {
        public int fin_id { get; set; }
        public int employee_id { get; set; }
        public int salary { get; set; }
        public int housing { get; set; }
        public int traveling { get; set; }
        public int transport { get; set; }
        public int food { get; set; }
    }
}
