//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees_signed_out
    {
        public int id { get; set; }
        public string employee_name { get; set; }
        public string terminal_ip { get; set; }
        public int user_id { get; set; }
        public int day { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public System.DateTime att_date { get; set; }
        public string signed_in { get; set; }
    }
}
