//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class empolyee_absents
    {
        public string machine_ip { get; set; }
        public int employee_id { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public float absents { get; set; }
    }
}
