//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class insuranceconcession
    {
        public int ConcessionID { get; set; }
        public int ProgramID { get; set; }
        public int MinYears { get; set; }
        public decimal Amount { get; set; }
    }
}
