//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurancerate
    {
        public int RateID { get; set; }
        public int ProgramID { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public int Value { get; set; }
        public int DependantValue { get; set; }
    }
}
