//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurancelistitem
    {
        public int ItemID { get; set; }
        public int ListID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public decimal SchoolShare { get; set; }
        public string Group { get; set; }
    }
}
