//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class insuranceprogram
    {
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public int ProviderID { get; set; }
        public string PolicyNumber { get; set; }
    }
}
