//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int status { get; set; }
        public int id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime loan_date { get; set; }
        public int loan_value { get; set; }
    }
}
