//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldEntities : DbContext
    {
        public OldEntities()
            : base("name=OldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<department> departments { get; set; }
        public DbSet<employee_types> employee_types { get; set; }
        public DbSet<employee_data> employee_data { get; set; }
        public DbSet<loan> loans { get; set; }
        public DbSet<penalty> penalties { get; set; }
        public DbSet<employee_trans> employee_trans { get; set; }
        public DbSet<boun> bouns { get; set; }
        public DbSet<absence> absences { get; set; }
        public DbSet<absent> absents { get; set; }
        public DbSet<borrow> borrows { get; set; }
        public DbSet<bus_drivers_and_supervisors> bus_drivers_and_supervisors { get; set; }
        public DbSet<bus_users_bonous> bus_users_bonous { get; set; }
        public DbSet<bus_users_cuts> bus_users_cuts { get; set; }
        public DbSet<bus_users_monthly_salaries> bus_users_monthly_salaries { get; set; }
        public DbSet<employee_att> employee_att { get; set; }
        public DbSet<employee_fin> employee_fin { get; set; }
        public DbSet<employee_salaries> employee_salaries { get; set; }
        public DbSet<employee_salaries_hist> employee_salaries_hist { get; set; }
        public DbSet<employee_status> employee_status { get; set; }
        public DbSet<employeedependant> employeedependants { get; set; }
        public DbSet<employees_ids> employees_ids { get; set; }
        public DbSet<employees_signed_out> employees_signed_out { get; set; }
        public DbSet<empolyee_absents> empolyee_absents { get; set; }
        public DbSet<empolyee_points> empolyee_points { get; set; }
        public DbSet<insuranceconcession> insuranceconcessions { get; set; }
        public DbSet<insurancelist> insurancelists { get; set; }
        public DbSet<insurancelistitem> insurancelistitems { get; set; }
        public DbSet<insuranceprogram> insuranceprograms { get; set; }
        public DbSet<insuranceprovider> insuranceproviders { get; set; }
        public DbSet<insurancerate> insurancerates { get; set; }
        public DbSet<lating> latings { get; set; }
        public DbSet<paper> papers { get; set; }
        public DbSet<salaries_monthly> salaries_monthly { get; set; }
        public DbSet<salaries_monthly_facts> salaries_monthly_facts { get; set; }
        public DbSet<salaries_users> salaries_users { get; set; }
        public DbSet<sector> sectors { get; set; }
        public DbSet<setting> settings { get; set; }
        public DbSet<shift> shifts { get; set; }
        public DbSet<sis_vacancies> sis_vacancies { get; set; }
        public DbSet<terminal> terminals { get; set; }
        public DbSet<vacation> vacations { get; set; }
    }
}
