//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaries_users
    {
        public int users_id { get; set; }
        public string users_name { get; set; }
        public string users_full_name { get; set; }
        public string users_pwd { get; set; }
        public Nullable<int> users_type { get; set; }
        public int user_school { get; set; }
        public string users_creation { get; set; }
        public string users_comment { get; set; }
    }
}
