//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaries_monthly_facts
    {
        public string employee_name { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public Nullable<int> salary { get; set; }
        public string department_name { get; set; }
        public Nullable<int> ex_employee { get; set; }
        public Nullable<int> enc_salary { get; set; }
        public Nullable<float> points { get; set; }
        public Nullable<double> points_val { get; set; }
        public Nullable<double> absents { get; set; }
        public Nullable<double> absents_val { get; set; }
        public Nullable<double> loans { get; set; }
        public Nullable<double> pen { get; set; }
        public Nullable<double> pen_val { get; set; }
        public Nullable<double> bon { get; set; }
        public Nullable<double> bon_val { get; set; }
        public Nullable<double> insurance { get; set; }
        public Nullable<double> housing { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> is_adjust { get; set; }
        public double atm { get; set; }
        public double tax { get; set; }
        public Nullable<int> HealthInsurance { get; set; }
    }
}
