//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaries_monthly
    {
        public int employee_id { get; set; }
        public string terminal_id { get; set; }
        public int user_id { get; set; }
        public int month { get; set; }
        public int year { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<float> points { get; set; }
        public Nullable<int> points_val { get; set; }
        public Nullable<int> absents { get; set; }
        public Nullable<int> absents_val { get; set; }
        public Nullable<int> loans { get; set; }
        public Nullable<int> pen { get; set; }
        public Nullable<int> pen_val { get; set; }
        public int bon { get; set; }
        public int bon_val { get; set; }
        public int insurance { get; set; }
        public int housing { get; set; }
        public Nullable<int> total { get; set; }
        public int is_adjust { get; set; }
        public int AutoID { get; set; }
    }
}
