//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int shift_id { get; set; }
        public string shift_name { get; set; }
        public System.TimeSpan sat_from { get; set; }
        public System.TimeSpan sat_to { get; set; }
        public System.TimeSpan sun_from { get; set; }
        public System.TimeSpan sun_to { get; set; }
        public System.TimeSpan mon_from { get; set; }
        public System.TimeSpan mon_to { get; set; }
        public System.TimeSpan tue_from { get; set; }
        public System.TimeSpan tue_to { get; set; }
        public System.TimeSpan wed_from { get; set; }
        public System.TimeSpan wed_to { get; set; }
        public System.TimeSpan thr_from { get; set; }
        public System.TimeSpan thr_to { get; set; }
        public System.TimeSpan fri_from { get; set; }
        public System.TimeSpan fri_to { get; set; }
        public int sat_in { get; set; }
        public int sun_in { get; set; }
        public int mon_in { get; set; }
        public int tue_in { get; set; }
        public int wed_in { get; set; }
        public int thr_in { get; set; }
        public int fri_in { get; set; }
    }
}
