//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.OldModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_vacancies
    {
        public int sis_vacancy_id { get; set; }
        public int school_id { get; set; }
        public string sis_vacancy_name { get; set; }
        public System.DateTime sis_vacancy_date_from { get; set; }
        public System.DateTime sis_vacancy_date_to { get; set; }
        public string sis_vacancy_comment { get; set; }
    }
}
