//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Driver {
  using System;
  using System.Data.Entity;
  using System.Data.Entity.Infrastructure;
  using System.Data.Entity.Core.Objects;
  using System.Linq;
  using System.Data;
  using System.Data.SqlClient;

  public partial class Entities : DbContext {
    public Entities()
        : base("name=Entities") {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder) {
      throw new UnintentionalCodeFirstException();
    }


    public virtual void EmployeeDeleteDuplicateAttendance(System.DateTime startDate, System.DateTime endDate, DataTable employeeIds) {
      var startDateParam = new SqlParameter("startDate", SqlDbType.Date);
      startDateParam.Value = startDate;

      var endDateParam = new SqlParameter("endDate", SqlDbType.Date);
      endDateParam.Value = endDate;

      var employeeIdsParam = new SqlParameter("employeeIDList", SqlDbType.Structured);
      employeeIdsParam.Value = employeeIds;
      employeeIdsParam.TypeName = employeeIds.GetType().Name;

      this.Database.ExecuteSqlCommand("exec [HR].[EmployeeDeleteDuplicateAttendance] @startDate, @endDate, @employeeIDList;", 
        startDateParam, endDateParam, employeeIdsParam);
    }
  }
}
