//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.EmployeeTerminals.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTerminalTransaction
    {
        public int TransactionID { get; set; }
        public string TerminalIP { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
