//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.EmployeeTerminals.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTerminal
    {
        public int TerminalID { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string IP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> Password { get; set; }
    }
}
