//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.EmployeeBankAccounts = new HashSet<EmployeeBankAccount>();
        }
    
        public int BankID { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
    
        public virtual ICollection<EmployeeBankAccount> EmployeeBankAccounts { get; set; }
    }
}
