//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactAddresses = new HashSet<ContactAddress>();
            this.ContactNumbers = new HashSet<ContactNumber>();
            this.Employees = new HashSet<Employee>();
            this.ContactEmails = new HashSet<ContactEmail>();
        }
    
        public int ContactID { get; set; }
    
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
        public virtual ICollection<ContactNumber> ContactNumbers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<ContactEmail> ContactEmails { get; set; }
    }
}
