//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEmail
    {
        public int EmailID { get; set; }
        public int ContactID { get; set; }
        public string Reference { get; set; }
        public string Email { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
