//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public EmployeeList()
        {
            this.Employees = new HashSet<Employee>();
            this.EmployeeDepartmentLists = new HashSet<EmployeeDepartmentList>();
            this.EmployeePositionLists = new HashSet<EmployeePositionList>();
        }
    
        public int ListID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeDepartmentList> EmployeeDepartmentLists { get; set; }
        public virtual ICollection<EmployeePositionList> EmployeePositionLists { get; set; }
    }
}
