//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMedicalClaimType
    {
        public EmployeeMedicalClaimType()
        {
            this.EmployeeMedicalClaims = new HashSet<EmployeeMedicalClaim>();
        }
    
        public int TypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EmployeeMedicalClaim> EmployeeMedicalClaims { get; set; }
    }
}
