//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMedicalRequest
    {
        public EmployeeMedicalRequest()
        {
            this.EmployeeMedicalRequestDependants = new HashSet<EmployeeMedicalRequestDependant>();
            this.EmployeeMedicalRequestEmployees = new HashSet<EmployeeMedicalRequestEmployee>();
        }
    
        public int RequestID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProgramID { get; set; }
        public int TypeID { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    
        public virtual EmployeeMedicalProgram EmployeeMedicalProgram { get; set; }
        public virtual ICollection<EmployeeMedicalRequestDependant> EmployeeMedicalRequestDependants { get; set; }
        public virtual ICollection<EmployeeMedicalRequestEmployee> EmployeeMedicalRequestEmployees { get; set; }
        public virtual EmployeeMedicalRequestType EmployeeMedicalRequestType { get; set; }
    }
}
