//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMedicalClaim
    {
        public EmployeeMedicalClaim()
        {
            this.EmployeeMedicalClaimDocuments = new HashSet<EmployeeMedicalClaimDocument>();
        }
    
        public int ClaimID { get; set; }
        public int CertificateID { get; set; }
        public string Reference { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TypeID { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public string Notes { get; set; }
    
        public virtual EmployeeMedicalCertificate EmployeeMedicalCertificate { get; set; }
        public virtual ICollection<EmployeeMedicalClaimDocument> EmployeeMedicalClaimDocuments { get; set; }
        public virtual EmployeeMedicalClaimType EmployeeMedicalClaimType { get; set; }
    }
}
