//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEarning
    {
        public int EarningID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Month { get; set; }
        public Nullable<System.DateTime> CalculationDateUtc { get; set; }
        public int Salary { get; set; }
        public int Housing { get; set; }
        public int Travel { get; set; }
        public int Social { get; set; }
        public int Medical { get; set; }
        public int Taxes { get; set; }
        public int UnemploymentDays { get; set; }
        public decimal DeductionPoints { get; set; }
        public int DeductionValues { get; set; }
        public int AbsenceDays { get; set; }
        public int AbsenceExtraDays { get; set; }
        public decimal AttendancePoints { get; set; }
        public decimal TimeOffPoints { get; set; }
        public int Loans { get; set; }
        public decimal BonusPoints { get; set; }
        public int BonusValues { get; set; }
        public decimal OvertimePoints { get; set; }
        public int Allowance { get; set; }
        public int Expenses { get; set; }
        public bool IsEdited { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
