//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public EmployeeAttendance()
        {
            this.EmployeeAttendanceTimeOffs = new HashSet<EmployeeAttendanceTimeOff>();
        }
    
        public int AttendanceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<decimal> InPoints { get; set; }
        public Nullable<decimal> OutPoints { get; set; }
        public Nullable<int> AbsencePoints { get; set; }
        public Nullable<decimal> OvertimePoints { get; set; }
        public Nullable<int> ExtraAbsencePoints { get; set; }
        public bool IsEdited { get; set; }
        public bool IsLocked { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EmployeeAttendanceTimeOff> EmployeeAttendanceTimeOffs { get; set; }
    }
}
