//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOfficialDocumentType
    {
        public EmployeeOfficialDocumentType()
        {
            this.EmployeeOfficialDocuments = new HashSet<EmployeeOfficialDocument>();
            this.EmployeeDepartmentOfficialDocuments = new HashSet<EmployeeDepartmentOfficialDocument>();
        }
    
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsMale { get; set; }
        public bool IsFemale { get; set; }
        public bool IsLocal { get; set; }
        public bool IsForeigner { get; set; }
    
        public virtual ICollection<EmployeeOfficialDocument> EmployeeOfficialDocuments { get; set; }
        public virtual ICollection<EmployeeDepartmentOfficialDocument> EmployeeDepartmentOfficialDocuments { get; set; }
    }
}
