//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankAccount
    {
        public int EmployeeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNumber { get; set; }
        public string RoutingNumber { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
