//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBranch
    {
        public EmployeeBranch()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int BranchID { get; set; }
        public string Name { get; set; }
        public string ArabicName { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
