//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBonus
    {
        public int BonusID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> Value { get; set; }
        public bool Approved { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
