//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryUpdate
    {
        public int UpdateID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public int Salary { get; set; }
        public int Housing { get; set; }
        public int Travel { get; set; }
        public int Social { get; set; }
        public int Medical { get; set; }
        public int Taxes { get; set; }
        public int Allowance { get; set; }
        public int Expenses { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
