//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLoanInstallment
    {
        public int InstallmentID { get; set; }
        public int LoanID { get; set; }
        public System.DateTime Month { get; set; }
        public int Amount { get; set; }
    
        public virtual EmployeeLoan EmployeeLoan { get; set; }
    }
}
