//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMedicalProgram
    {
        public EmployeeMedicalProgram()
        {
            this.EmployeeMedicalConcessions = new HashSet<EmployeeMedicalConcession>();
            this.EmployeeMedicalRates = new HashSet<EmployeeMedicalRate>();
            this.EmployeeMedicalCertificates = new HashSet<EmployeeMedicalCertificate>();
            this.EmployeeMedicalProgramTemplates = new HashSet<EmployeeMedicalProgramTemplate>();
            this.EmployeeMedicalRequests = new HashSet<EmployeeMedicalRequest>();
        }
    
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public int ProviderID { get; set; }
        public string PolicyCode { get; set; }
    
        public virtual ICollection<EmployeeMedicalConcession> EmployeeMedicalConcessions { get; set; }
        public virtual EmployeeMedicalProvider EmployeeMedicalProvider { get; set; }
        public virtual ICollection<EmployeeMedicalRate> EmployeeMedicalRates { get; set; }
        public virtual ICollection<EmployeeMedicalCertificate> EmployeeMedicalCertificates { get; set; }
        public virtual ICollection<EmployeeMedicalProgramTemplate> EmployeeMedicalProgramTemplates { get; set; }
        public virtual ICollection<EmployeeMedicalRequest> EmployeeMedicalRequests { get; set; }
    }
}
