//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMedicalCertificate
    {
        public EmployeeMedicalCertificate()
        {
            this.Employees = new HashSet<Employee>();
            this.EmployeeDependants = new HashSet<EmployeeDependant>();
            this.EmployeeMedicalClaims = new HashSet<EmployeeMedicalClaim>();
        }
    
        public int CertificateID { get; set; }
        public string Code { get; set; }
        public int ProgramID { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<decimal> Concession { get; set; }
        public Nullable<int> Monthly { get; set; }
        public Nullable<int> Rate { get; set; }
        public string CancellationReason { get; set; }
        public string Owner { get; set; }
        public string RateType { get; set; }
    
        public virtual EmployeeMedicalProgram EmployeeMedicalProgram { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeDependant> EmployeeDependants { get; set; }
        public virtual ICollection<EmployeeMedicalClaim> EmployeeMedicalClaims { get; set; }
    }
}
