//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCustody
    {
        public int CustodyID { get; set; }
        public int EmployeeID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime Date { get; set; }
        public int Qty { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> RelinquishDate { get; set; }
    
        public virtual EmployeeCustodyItem EmployeeCustodyItem { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
