//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShift
    {
        public EmployeeShift()
        {
            this.Employees = new HashSet<Employee>();
            this.EmployeeShiftOverrides = new HashSet<EmployeeShiftOverride>();
        }
    
        public int ShiftID { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> SaturdaysFrom { get; set; }
        public Nullable<System.TimeSpan> SaturdaysTo { get; set; }
        public Nullable<System.TimeSpan> SundaysFrom { get; set; }
        public Nullable<System.TimeSpan> SundaysTo { get; set; }
        public Nullable<System.TimeSpan> MondaysFrom { get; set; }
        public Nullable<System.TimeSpan> MondaysTo { get; set; }
        public Nullable<System.TimeSpan> TuesdaysFrom { get; set; }
        public Nullable<System.TimeSpan> TuesdaysTo { get; set; }
        public Nullable<System.TimeSpan> WednesdaysFrom { get; set; }
        public Nullable<System.TimeSpan> WednesdaysTo { get; set; }
        public Nullable<System.TimeSpan> ThursdaysFrom { get; set; }
        public Nullable<System.TimeSpan> ThursdaysTo { get; set; }
        public Nullable<System.TimeSpan> FridaysFrom { get; set; }
        public Nullable<System.TimeSpan> FridaysTo { get; set; }
        public Nullable<int> LocalID { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeShiftOverride> EmployeeShiftOverrides { get; set; }
    }
}
