//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDependant
    {
        public EmployeeDependant()
        {
            this.EmployeeMedicalRequestDependants = new HashSet<EmployeeMedicalRequestDependant>();
        }
    
        public int DependantID { get; set; }
        public int EmployeeID { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string Type { get; set; }
        public Nullable<int> MedicalCertificateID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FamilyName { get; set; }
        public string ArabicFirstName { get; set; }
        public string ArabicMiddleName { get; set; }
        public string ArabicLastName { get; set; }
        public string ArabicFamilyName { get; set; }
    
        public virtual EmployeeMedicalCertificate EmployeeMedicalCertificate { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual ICollection<EmployeeMedicalRequestDependant> EmployeeMedicalRequestDependants { get; set; }
    }
}
