//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartmentList
    {
        public int DepartmentID { get; set; }
        public int ListID { get; set; }
        public Nullable<bool> IgnoreThis { get; set; }
    
        public virtual EmployeeDepartment EmployeeDepartment { get; set; }
        public virtual EmployeeList EmployeeList { get; set; }
    }
}
