//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public SystemLog()
        {
            this.SystemLogDatas = new HashSet<SystemLogData>();
        }
    
        public int LogID { get; set; }
        public Nullable<System.DateTime> DateTimeUtc { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Username { get; set; }
        public string Computer { get; set; }
        public string AppVersion { get; set; }
        public string Category { get; set; }
        public string Level { get; set; }
        public string Action { get; set; }
        public string Table { get; set; }
        public string References { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SystemLogData> SystemLogDatas { get; set; }
    }
}
