//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLogData
    {
        public int DataID { get; set; }
        public int LogID { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
    
        public virtual SystemLog SystemLog { get; set; }
    }
}
