//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Sync.NewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public View()
        {
            this.UserViews = new HashSet<UserView>();
            this.Views1 = new HashSet<View>();
        }
    
        public int ViewID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public string Path { get; set; }
        public string Params { get; set; }
        public Nullable<int> ParentViewID { get; set; }
        public string Assembly { get; set; }
    
        public virtual ICollection<UserView> UserViews { get; set; }
        public virtual ICollection<View> Views1 { get; set; }
        public virtual View View1 { get; set; }
    }
}
