//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csc.IntelliSchool.Assets.Resources.HumanResources", typeof(HumanResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated successfully..
        /// </summary>
        public static string Alert_CalculatedSuccessfully {
            get {
                return ResourceManager.GetString("Alert_CalculatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this type? Items linked to this type will be unlinked and will NOT be deleted.
        ///This cannot be undone..
        /// </summary>
        public static string Confirm_DeleteType {
            get {
                return ResourceManager.GetString("Confirm_DeleteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recalculate attendance for this employee?
        ///This cannot be undone..
        /// </summary>
        public static string Confirm_RecalculateAttendance {
            get {
                return ResourceManager.GetString("Confirm_RecalculateAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recalculate earning for this employee?
        ///This cannot be undone..
        /// </summary>
        public static string Confirm_RecalculateEarning {
            get {
                return ResourceManager.GetString("Confirm_RecalculateEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update earning for this employee?
        ///This cannot be undone..
        /// </summary>
        public static string Confirm_UpdateEarning {
            get {
                return ResourceManager.GetString("Confirm_UpdateEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This employee has one or more dependants. Append them to the request too?.
        /// </summary>
        public static string Medical_AppendDependantRequest {
            get {
                return ResourceManager.GetString("Medical_AppendDependantRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a medical certificate to an uncovered member..
        /// </summary>
        public static string Medical_DependantUncoveredMember {
            get {
                return ResourceManager.GetString("Medical_DependantUncoveredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate with the same code already exists..
        /// </summary>
        public static string Medical_ExistingCode {
            get {
                return ResourceManager.GetString("Medical_ExistingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template found..
        /// </summary>
        public static string Medical_NoTemplate {
            get {
                return ResourceManager.GetString("Medical_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependant, {0} ({1}).
        /// </summary>
        public static string Medical_TypeDependant {
            get {
                return ResourceManager.GetString("Medical_TypeDependant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member, ID: {0}.
        /// </summary>
        public static string Medical_TypeMember {
            get {
                return ResourceManager.GetString("Medical_TypeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncovered.
        /// </summary>
        public static string Medical_Uncovered {
            get {
                return ResourceManager.GetString("Medical_Uncovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now ready to recalculate attendance for this terminal. Are you sure you want to continue?
        ///This cannot be undone..
        /// </summary>
        public static string Terminal_CalculateAttendance {
            get {
                return ResourceManager.GetString("Terminal_CalculateAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to fetch transactions of this terminal?.
        /// </summary>
        public static string Terminal_ConfirmFetch {
            get {
                return ResourceManager.GetString("Terminal_ConfirmFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch transactions from this terminal..
        /// </summary>
        public static string Terminal_FetchFailed {
            get {
                return ResourceManager.GetString("Terminal_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done fetching {0:N0} entry(ies) for {1:N0} user(s)..
        /// </summary>
        public static string Terminal_FetchSuccess {
            get {
                return ResourceManager.GetString("Terminal_FetchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done fetching {0:N0} entry(ies) for {1:N0} user(s). Errors occcurred..
        /// </summary>
        public static string Terminal_FetchSuccessWithError {
            get {
                return ResourceManager.GetString("Terminal_FetchSuccessWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals-Only.
        /// </summary>
        public static string Terminal_TerminalsOnly {
            get {
                return ResourceManager.GetString("Terminal_TerminalsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This terminal cannot be fetched. Please ensure that all data is entered correctly..
        /// </summary>
        public static string Terminal_Unsupported {
            get {
                return ResourceManager.GetString("Terminal_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This terminal is already used with another employee..
        /// </summary>
        public static string Terminal_UserExists {
            get {
                return ResourceManager.GetString("Terminal_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to terminate this employee?.
        /// </summary>
        public static string Terminate_Confirm {
            get {
                return ResourceManager.GetString("Terminate_Confirm", resourceCulture);
            }
        }
    }
}
