//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csc.IntelliSchool.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Csc.IntelliSchool.Assets.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No option selected..
        /// </summary>
        public static string Alert_NoOptionSelected {
            get {
                return ResourceManager.GetString("Alert_NoOptionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected items!.
        /// </summary>
        public static string Alert_NoSelectedItems {
            get {
                return ResourceManager.GetString("Alert_NoSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select month..
        /// </summary>
        public static string Alert_NoSelectedMonth {
            get {
                return ResourceManager.GetString("Alert_NoSelectedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review data entered and try again..
        /// </summary>
        public static string Error_Validation {
            get {
                return ResourceManager.GetString("Error_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File generated successfully and saved to &apos;{0}&apos;. Continue opening this file?.
        /// </summary>
        public static string File_Generated_Confirm {
            get {
                return ResourceManager.GetString("File_Generated_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully to &apos;{0}&apos;..
        /// </summary>
        public static string File_Saved {
            get {
                return ResourceManager.GetString("File_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove photo?.
        /// </summary>
        public static string Photo_Confirm_Remove {
            get {
                return ResourceManager.GetString("Photo_Confirm_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Text_All {
            get {
                return ResourceManager.GetString("Text_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        public static string Text_Everything {
            get {
                return ResourceManager.GetString("Text_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Text_Export {
            get {
                return ResourceManager.GetString("Text_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string Text_NewItem {
            get {
                return ResourceManager.GetString("Text_NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlisted.
        /// </summary>
        public static string Text_Unlisted {
            get {
                return ResourceManager.GetString("Text_Unlisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Item.
        /// </summary>
        public static string Text_UpdateItem {
            get {
                return ResourceManager.GetString("Text_UpdateItem", resourceCulture);
            }
        }
    }
}
